source 'https://rubygems.org'

gem 'rake'
gem 'puppet-lint'
gem 'rspec-puppet', :github => 'rodjek/rspec-puppet'
gem 'rspec-system-puppet'
gem 'puppetlabs_spec_helper'
gem 'travis'
gem 'travis-lint'
gem 'puppet-syntax'
gem 'puppet'
gem 'vagrant-wrapper'
