name 'nilo72-owncloud'
version '0.0.1'
source 'git://github.com/haw-hh-ai-lab/puppet-owncloud'
author 'Oliver Neumann'
license 'Apache 2.0'
summary 'Owncloud environment db and app servers'
description "Owncloud environment db and app servers"
project_page 'https://github.com/haw-hh-ai-lab/puppet-owncloud'
dependency 'puppetlabs/apt', '1.4.1'
dependency 'puppetlabs/stdlib', '4.2.1'
dependency 'puppetlabs/mysql', '2.2.1'
dependency 'cypherfox/nagios', '0.1.0'
dependency 'puppetlabs/apache', '1.0.1'
